import sys
from threading import Thread

import cv2
import numpy
from PIL import Image

from global_data import GlobalData


class CgneThread(Thread):

    def __init__(self, global_data: GlobalData, g: numpy.ndarray):
        super().__init__()
        self.global_data = global_data
        self.signal = g
        self.start()

    def run(self):

        loop_maximum = 30

        loop_counter = 0

        f_next = 0

        error = 0

        f_old = numpy.zeros_like(numpy.matmul(self.global_data.get_transpose_h(), self.signal))

        r_old = self.signal - numpy.matmul(self.global_data.H, f_old)

        p_old = numpy.matmul(self.global_data.get_transpose_h(), r_old)

        for counter in range(loop_maximum):

            a_i = numpy.matmul(r_old.transpose(), r_old, dtype=float) / \
                  numpy.matmul(p_old.transpose(), p_old)

            f_next = f_old + p_old * a_i

            r_next = r_old - numpy.matmul(self.global_data.H, p_old) * a_i

            beta = numpy.divide(numpy.matmul(r_next.transpose(), r_next),
                                numpy.matmul(r_old.transpose(), r_old))

            p_next = numpy.matmul(self.global_data.get_transpose_h(), r_next) + p_old * beta

            error = numpy.absolute(numpy.linalg.norm(
                r_next, ord=2) - numpy.linalg.norm(r_old, ord=2))

            p_old = p_next

            f_old = f_next

            r_old = r_next

            loop_counter = counter

            if error < self.global_data.minimal_error:
                break

        sys.stdout.write(" [X] Data about image generated by cgne thread -> actual error: " + str(
            error) + "  expected error: <" + str(self.global_data.minimal_error) + "  loop counter: " + str(
            loop_counter) + "\n")

        f_reshaped = f_next.reshape(60, 60)

        normalized = cv2.normalize(src=f_reshaped, alpha=0, beta=255, dst=numpy.zeros_like(f_reshaped),
                                   norm_type=cv2.NORM_MINMAX)

        first_image = Image.fromarray(numpy.uint8(normalized.transpose()), mode='L')

        first_image.save('./images/last_generated_image_by_cgne_algorithm.bmp')

        del self
